const fs = require('fs');
const path = require('path');

const pagesDir = path.join(__dirname, 'src', 'pages');
const langDir = path.join(pagesDir, '[lang]');

if (!fs.existsSync(langDir)) fs.mkdirSync(langDir, { recursive: true });

const pages = {
  features: {
    en: { title: "Features", html: "<h1>Features</h1><ul><li><strong>Automatic Capture:</strong> Silently extracts and saves artifacts as you browse your claude.ai chats. (5 artifact types)</li><li><strong>Visual Gallery:</strong> Browse, search, and manage all your generated content with filters.</li><li><strong>Batch Export:</strong> Download individual files or export your entire artifact library as a ZIP.</li><li><strong>Pin & Organize:</strong> Pin your most important artifacts.</li><li><strong>JSON Backup Export:</strong> Export your data safely.</li><li><strong>100% Private:</strong> Zero tracking.</li><li><strong>Localization & Theming:</strong> Dark/light theme, 5-language UI with full Arabic RTL.</li></ul>" },
    ar: { title: "الميزات", html: "<h1>الميزات</h1><ul><li><strong>التقاط تلقائي:</strong> يستخرج ويحفظ القطع الأثرية بصمت (5 أنواع).</li><li><strong>معرض مرئي:</strong> تصفح وابحث وقم بإدارة المحتوى الخاص بك مع فلاتر.</li><li><strong>تصدير دفعي:</strong> تصدير بصيغة ZIP.</li><li><strong>تثبيت وتنظيم:</strong> تثبيت القطع الأثرية المهمة.</li><li><strong>تصدير نسخة احتياطية JSON:</strong> تصدير بياناتك بأمان.</li><li><strong>خاص 100%:</strong> بدون تتبع.</li><li><strong>الترجمة والمظهر:</strong> مظهر داكن/فاتح، واجهة بـ 5 لغات مع دعم كامل للغة العربية.</li></ul>" },
    fr: { title: "Fonctionnalités", html: "<h1>Fonctionnalités</h1><ul><li><strong>Capture automatique :</strong> Extrait et enregistre silencieusement les artefacts (5 types).</li><li><strong>Galerie visuelle :</strong> Parcourez, recherchez et gérez avec des filtres.</li><li><strong>Exportation par lots :</strong> Exportation ZIP.</li><li><strong>Épingler et organiser :</strong> Épinglez les artefacts importants.</li><li><strong>Exportation JSON :</strong> Sauvegarde sécurisée.</li><li><strong>100% Privé :</strong> Aucun suivi.</li><li><strong>Localisation et thèmes :</strong> Thème clair/sombre, interface en 5 langues.</li></ul>" },
    es: { title: "Características", html: "<h1>Características</h1><ul><li><strong>Captura automática:</strong> Extrae y guarda artefactos silenciosamente (5 tipos).</li><li><strong>Galería visual:</strong> Navega, busca y gestiona con filtros.</li><li><strong>Exportación por lotes:</strong> Exportación ZIP.</li><li><strong>Fijar y organizar:</strong> Fija artefactos importantes.</li><li><strong>Exportación JSON:</strong> Copia de seguridad.</li><li><strong>100% Privado:</strong> Sin rastreo.</li><li><strong>Localización y Temas:</strong> Tema claro/oscuro, interfaz en 5 idiomas.</li></ul>" },
    pt: { title: "Recursos", html: "<h1>Recursos</h1><ul><li><strong>Captura automática:</strong> Extrai e salva artefatos silenciosamente (5 tipos).</li><li><strong>Galeria visual:</strong> Navegue, pesquise e gerencie com filtros.</li><li><strong>Exportação em lote:</strong> Exportação ZIP.</li><li><strong>Fixar e organizar:</strong> Fixe artefatos importantes.</li><li><strong>Exportação JSON:</strong> Backup seguro.</li><li><strong>100% Privado:</strong> Zero rastreamento.</li><li><strong>Localização e Temas:</strong> Tema claro/escuro, interface em 5 idiomas.</li></ul>" }
  },
  faq: {
    schema: true,
    en: { title: "FAQ", html: "<h1>Frequently Asked Questions</h1><h3>Is it free?</h3><p>Yes, Abrium is 100% free with no paid tiers.</p><h3>Does it read my conversations?</h3><p>No. It only reads Artifact content, not your prompts or unrelated conversations.</p><h3>Why Code view and not Preview?</h3><p>For security and simplicity, we show the raw code rather than rendering potentially unsafe previews.</p><h3>Where is data stored?</h3><p>All data is stored purely in your local browser storage (chrome.storage.local).</p><h3>What about the diagnostic tools in the repo?</h3><p>The repository's diagnostic tools are safe to run and collect no personal data, providing only system readiness reports.</p>" },
    ar: { title: "الأسئلة الشائعة", html: "<h1>الأسئلة الشائعة</h1><h3>هل هو مجاني؟</h3><p>نعم، أبريوم مجاني 100% بدون أي فئات مدفوعة.</p><h3>هل يقرأ محادثاتي؟</h3><p>لا. يقرأ محتوى القطع الأثرية فقط، وليس مطالباتك.</p><h3>لماذا عرض الكود وليس المعاينة؟</h3><p>لأسباب أمنية، نعرض الكود الخام بدلاً من معاينات قد تكون غير آمنة.</p><h3>أين يتم تخزين البيانات؟</h3><p>يتم تخزين جميع البيانات محلياً في متصفحك.</p><h3>ماذا عن الأدوات التشخيصية في المستودع؟</h3><p>أدوات المستودع آمنة ولا تجمع بيانات شخصية.</p>" },
    fr: { title: "FAQ", html: "<h1>Foire Aux Questions</h1><h3>Est-ce gratuit ?</h3><p>Oui, 100% gratuit, sans abonnement.</p><h3>Lit-il mes conversations ?</h3><p>Non. Uniquement le contenu des Artefacts.</p><h3>Pourquoi la vue Code et non Aperçu ?</h3><p>Pour des raisons de sécurité, nous affichons le code brut.</p><h3>Où sont stockées les données ?</h3><p>Dans le stockage local de votre navigateur.</p><h3>Qu'en est-il des outils de diagnostic ?</h3><p>Ils sont sûrs et ne collectent aucune donnée personnelle.</p>" },
    es: { title: "Preguntas Frecuentes", html: "<h1>Preguntas Frecuentes</h1><h3>¿Es gratis?</h3><p>Sí, 100% gratis.</p><h3>¿Lee mis conversaciones?</h3><p>No. Solo el contenido de los Artefactos.</p><h3>¿Por qué vista de Código y no Vista Previa?</h3><p>Por seguridad, mostramos el código sin formato.</p><h3>¿Dónde se almacenan los datos?</h3><p>En el almacenamiento local de tu navegador.</p><h3>¿Qué pasa con las herramientas de diagnóstico?</h3><p>Son seguras y no recopilan datos personales.</p>" },
    pt: { title: "FAQ", html: "<h1>Perguntas Frequentes</h1><h3>É gratuito?</h3><p>Sim, 100% gratuito.</p><h3>Lê minhas conversas?</h3><p>Não. Apenas o conteúdo dos Artefatos.</p><h3>Por que visualização de Código e não Pré-visualização?</h3><p>Por segurança, mostramos o código bruto.</p><h3>Onde os dados são armazenados?</h3><p>No armazenamento local do seu navegador.</p><h3>E as ferramentas de diagnóstico?</h3><p>São seguras e não coletam dados pessoais.</p>" }
  },
  download: {
    en: { title: "Download", html: "<h1>Download Abrium</h1><p>Get the extension from the Chrome Web Store:</p><br/><p><a href='https://chrome.google.com/webstore/placeholder-abrium-url' class='button' target='_blank'>Download on Chrome Web Store (PLACEHOLDER)</a></p><br/><p><em>Note: The extension is not yet published. This link is a placeholder.</em></p>" },
    ar: { title: "تنزيل", html: "<h1>تنزيل أبريوم</h1><br/><p><a href='https://chrome.google.com/webstore/placeholder-abrium-url' class='button' target='_blank'>تنزيل (رابط مؤقت)</a></p>" },
    fr: { title: "Télécharger", html: "<h1>Télécharger Abrium</h1><br/><p><a href='https://chrome.google.com/webstore/placeholder-abrium-url' class='button' target='_blank'>Télécharger (Lien fictif)</a></p>" },
    es: { title: "Descargar", html: "<h1>Descargar Abrium</h1><br/><p><a href='https://chrome.google.com/webstore/placeholder-abrium-url' class='button' target='_blank'>Descargar (Enlace de marcador de posición)</a></p>" },
    pt: { title: "Baixar", html: "<h1>Baixar Abrium</h1><br/><p><a href='https://chrome.google.com/webstore/placeholder-abrium-url' class='button' target='_blank'>Baixar (Link de espaço reservado)</a></p>" }
  },
  changelog: {
    en: { title: "Changelog", html: "<h1>Changelog</h1><ul><li><strong>v0.1.0</strong> &mdash; Initial release.</li></ul>" },
    ar: { title: "سجل التغييرات", html: "<h1>سجل التغييرات</h1><ul><li><strong>v0.1.0</strong> &mdash; الإصدار الأولي.</li></ul>" },
    fr: { title: "Journal des modifications", html: "<h1>Journal des modifications</h1><ul><li><strong>v0.1.0</strong> &mdash; Sortie initiale.</li></ul>" },
    es: { title: "Registro de cambios", html: "<h1>Registro de cambios</h1><ul><li><strong>v0.1.0</strong> &mdash; Lanzamiento inicial.</li></ul>" },
    pt: { title: "Registro de alterações", html: "<h1>Registro de alterações</h1><ul><li><strong>v0.1.0</strong> &mdash; Lançamento inicial.</li></ul>" }
  },
  terms: {
    en: { title: "Terms of Service", html: "<h1>Terms of Service</h1><p>Welcome to Abrium. By using our free extension, you agree to our basic usage terms. Abrium is provided open-source and \"as is\" to help you manage your artifacts locally. We simply ask that you use the tool responsibly. Your data is yours.</p>" },
    ar: { title: "شروط الخدمة", html: "<h1>شروط الخدمة</h1><p>مرحباً بك في أبريوم. الأداة مقدمة مجاناً لمساعدتك في إدارة بياناتك محلياً. نطلب منك استخدامها بمسؤولية.</p>" },
    fr: { title: "Conditions d'utilisation", html: "<h1>Conditions d'utilisation</h1><p>Bienvenue sur Abrium. L'outil est gratuit pour gérer vos artefacts localement. Utilisez-le de manière responsable.</p>" },
    es: { title: "Términos de Servicio", html: "<h1>Términos de Servicio</h1><p>Bienvenido a Abrium. La herramienta es gratuita para gestionar tus artefactos localmente. Úsala con responsabilidad.</p>" },
    pt: { title: "Termos de Serviço", html: "<h1>Termos de Serviço</h1><p>Bem-vindo ao Abrium. A ferramenta é gratuita para gerenciar seus artefatos localmente. Use-a com responsabilidade.</p>" }
  },
  contact: {
    en: { title: "Contact Us", html: "<h1>Contact Us</h1><p><a href='https://github.com/yourusername/abrium' target='_blank'>Report an issue on GitHub</a></p><br/><p><a href='https://patreon.com/placeholder-abrium' target='_blank'>Support us on Patreon (PLACEHOLDER)</a></p>" },
    ar: { title: "اتصل بنا", html: "<h1>اتصل بنا</h1><p><a href='https://github.com/yourusername/abrium' target='_blank'>أبلغ عن مشكلة في جيت هاب</a></p><br/><p><a href='https://patreon.com/placeholder-abrium' target='_blank'>ادعمنا على باتريون (رابط مؤقت)</a></p>" },
    fr: { title: "Nous Contacter", html: "<h1>Nous Contacter</h1><p><a href='https://github.com/yourusername/abrium' target='_blank'>Signaler un problème sur GitHub</a></p><br/><p><a href='https://patreon.com/placeholder-abrium' target='_blank'>Soutenez-nous sur Patreon (Fictif)</a></p>" },
    es: { title: "Contáctanos", html: "<h1>Contáctanos</h1><p><a href='https://github.com/yourusername/abrium' target='_blank'>Reportar un problema en GitHub</a></p><br/><p><a href='https://patreon.com/placeholder-abrium' target='_blank'>Apóyanos en Patreon (Marcador)</a></p>" },
    pt: { title: "Contate-nos", html: "<h1>Contate-nos</h1><p><a href='https://github.com/yourusername/abrium' target='_blank'>Relatar um problema no GitHub</a></p><br/><p><a href='https://patreon.com/placeholder-abrium' target='_blank'>Apoie-nos no Patreon (Marcador)</a></p>" }
  },
  'cookie-preferences': {
    en: { title: "Cookie Preferences", html: "<h1>Cookie Preferences</h1><p>You can change your Google Analytics 4 tracking preferences here.</p><br/><div style='display:flex;gap:var(--space-4)'><button id='pref-reject' class='button button-outline'>Reject All</button><button id='pref-accept' class='button'>Accept All</button></div><script>document.addEventListener('DOMContentLoaded', () => { document.getElementById('pref-accept').addEventListener('click', () => { localStorage.setItem('cookie_consent', 'accepted'); alert('Preferences updated: Accepted'); location.reload(); }); document.getElementById('pref-reject').addEventListener('click', () => { localStorage.setItem('cookie_consent', 'rejected'); alert('Preferences updated: Rejected'); location.reload(); }); });</script>" },
    ar: { title: "تفضيلات ملفات تعريف الارتباط", html: "<h1>تفضيلات ملفات تعريف الارتباط</h1><p>يمكنك تغيير تفضيلات تتبع Google Analytics 4 هنا.</p><br/><div style='display:flex;gap:var(--space-4)'><button id='pref-reject' class='button button-outline'>رفض الكل</button><button id='pref-accept' class='button'>قبول الكل</button></div><script>document.addEventListener('DOMContentLoaded', () => { document.getElementById('pref-accept').addEventListener('click', () => { localStorage.setItem('cookie_consent', 'accepted'); alert('تم التحديث: قبول'); location.reload(); }); document.getElementById('pref-reject').addEventListener('click', () => { localStorage.setItem('cookie_consent', 'rejected'); alert('تم التحديث: رفض'); location.reload(); }); });</script>" },
    fr: { title: "Préférences de cookies", html: "<h1>Préférences de cookies</h1><p>Modifiez vos préférences Google Analytics 4 ici.</p><br/><div style='display:flex;gap:var(--space-4)'><button id='pref-reject' class='button button-outline'>Tout refuser</button><button id='pref-accept' class='button'>Tout accepter</button></div><script>document.addEventListener('DOMContentLoaded', () => { document.getElementById('pref-accept').addEventListener('click', () => { localStorage.setItem('cookie_consent', 'accepted'); alert('Mise à jour : Accepté'); location.reload(); }); document.getElementById('pref-reject').addEventListener('click', () => { localStorage.setItem('cookie_consent', 'rejected'); alert('Mise à jour : Refusé'); location.reload(); }); });</script>" },
    es: { title: "Preferencias de cookies", html: "<h1>Preferencias de cookies</h1><p>Cambia tus preferencias de Google Analytics 4 aquí.</p><br/><div style='display:flex;gap:var(--space-4)'><button id='pref-reject' class='button button-outline'>Rechazar todo</button><button id='pref-accept' class='button'>Aceptar todo</button></div><script>document.addEventListener('DOMContentLoaded', () => { document.getElementById('pref-accept').addEventListener('click', () => { localStorage.setItem('cookie_consent', 'accepted'); alert('Actualizado: Aceptado'); location.reload(); }); document.getElementById('pref-reject').addEventListener('click', () => { localStorage.setItem('cookie_consent', 'rejected'); alert('Actualizado: Rechazado'); location.reload(); }); });</script>" },
    pt: { title: "Preferências de cookies", html: "<h1>Preferências de cookies</h1><p>Altere suas preferências do Google Analytics 4 aqui.</p><br/><div style='display:flex;gap:var(--space-4)'><button id='pref-reject' class='button button-outline'>Rejeitar tudo</button><button id='pref-accept' class='button'>Aceitar tudo</button></div><script>document.addEventListener('DOMContentLoaded', () => { document.getElementById('pref-accept').addEventListener('click', () => { localStorage.setItem('cookie_consent', 'accepted'); alert('Atualizado: Aceito'); location.reload(); }); document.getElementById('pref-reject').addEventListener('click', () => { localStorage.setItem('cookie_consent', 'rejected'); alert('Atualizado: Rejeitado'); location.reload(); }); });</script>" }
  }
};

for (const [page, data] of Object.entries(pages)) {
  const schemaStr = page === 'faq' ? "\nconst faqSchema = { \"@context\": \"https://schema.org\", \"@type\": \"FAQPage\", \"mainEntity\": [{ \"@type\": \"Question\", \"name\": \"Is it free?\", \"acceptedAnswer\": { \"@type\": \"Answer\", \"text\": \"Yes, Abrium is 100% free with no paid tiers.\" } }, { \"@type\": \"Question\", \"name\": \"Does it read my conversations?\", \"acceptedAnswer\": { \"@type\": \"Answer\", \"text\": \"No. It only reads Artifact content, not your prompts or unrelated conversations.\" } }] };\n" : (page === 'changelog' ? "\nconst changelogSchema = { \"@context\": \"https://schema.org\", \"@type\": \"ItemList\", \"itemListElement\": [ { \"@type\": \"ListItem\", \"position\": 1, \"name\": \"v0.1.0 - Initial release\" } ] };\n" : "");
  const schemaSlot = page === 'faq' ? '<script type="application/ld+json" set:html={JSON.stringify(faqSchema)} slot="head" />' : (page === 'changelog' ? '<script type="application/ld+json" set:html={JSON.stringify(changelogSchema)} slot="head" />' : '');
  
  const enContent = "---\nimport Layout from '../layouts/Layout.astro';\n" + schemaStr + "\n---\n<Layout title=\"" + data.en.title + "\" description=\"" + data.en.title + "\">\n  " + schemaSlot + "\n  " + data.en.html + "\n</Layout>\n";
  fs.writeFileSync(path.join(pagesDir, page + '.astro'), enContent);
  
  const translations = JSON.stringify({ ar: data.ar, fr: data.fr, es: data.es, pt: data.pt });
  const locContent = "---\nimport Layout from '../../layouts/Layout.astro';\n" + schemaStr + "\nexport function getStaticPaths() { return [ { params: { lang: 'ar' } }, { params: { lang: 'fr' } }, { params: { lang: 'es' } }, { params: { lang: 'pt' } } ]; }\nconst { lang } = Astro.params;\nconst translations = " + translations + ";\nconst t = translations[lang];\n---\n<Layout title={t.title} description={t.title}>\n  " + schemaSlot + "\n  <div set:html={t.html} />\n</Layout>\n";
  
  fs.writeFileSync(path.join(langDir, page + '.astro'), locContent);
}

const notFoundContent = "---\nimport Layout from '../layouts/Layout.astro';\n---\n<Layout title=\"404 - Not Found\" description=\"Page not found\">\n  <h1>404 - Not Found</h1>\n  <p>The page you are looking for does not exist.</p>\n  <br/>\n  <a href=\"/\" class=\"button\">Go Home</a>\n</Layout>\n";
fs.writeFileSync(path.join(pagesDir, '404.astro'), notFoundContent);
console.log('Pages generated successfully!');
